<?php
namespace App\Filament\Resources;
use App\Filament\Resources\LeaveRequestResource\Pages; use App\Modules\Leave\Interfaces\LeaveServiceInterface; use App\Modules\Leave\Enums\LeaveType; use App\Modules\Leave\Models\Enums\RequestStatus; use App\Modules\Leave\Models\LeaveRequest; use Filament\Forms; use Filament\Notifications\Notification; use Filament\Forms\Form; use Filament\Resources\Resource; use Filament\Tables; use Filament\Tables\Table;
class LeaveRequestResource extends Resource
{
    protected static ?string $model=LeaveRequest::class; protected static ?string $navigationIcon='heroicon-o-calendar-days'; protected static ?string $navigationGroup='Nhân sự'; protected static ?string $modelLabel='Đơn nghỉ phép'; protected static ?string $pluralModelLabel='Đơn nghỉ phép';
    public static function form(Form $form): Form { return $form->schema([Forms\Components\Select::make('user_id')->label('Nhân viên')->relationship('user','name')->searchable()->preload()->required(), Forms\Components\Select::make('leave_type')->label('Loại nghỉ')->options(self::enumOptions(LeaveType::class))->required(), Forms\Components\DatePicker::make('start_date')->label('Từ ngày')->required(), Forms\Components\DatePicker::make('end_date')->label('Đến ngày')->required(), Forms\Components\Select::make('status')->label('Trạng thái')->options(self::enumOptions(RequestStatus::class))->required(), Forms\Components\Textarea::make('reason')->label('Lý do')->columnSpanFull(), Forms\Components\Textarea::make('rejection_reason')->label('Lý do từ chối')->columnSpanFull()])->columns(2); }
    public static function table(Table $table): Table { return $table->columns([Tables\Columns\TextColumn::make('user.name')->label('Nhân viên')->searchable(), Tables\Columns\TextColumn::make('leave_type')->label('Loại nghỉ')->formatStateUsing(fn($state)=>$state instanceof LeaveType?$state->label():LeaveType::tryFrom((int)$state)?->label()), Tables\Columns\TextColumn::make('start_date')->label('Từ')->date('d/m/Y'), Tables\Columns\TextColumn::make('end_date')->label('Đến')->date('d/m/Y'), Tables\Columns\TextColumn::make('status')->label('Trạng thái')->formatStateUsing(fn($state)=>$state instanceof RequestStatus?$state->label():RequestStatus::tryFrom((int)$state)?->label())->badge()])->actions([Tables\Actions\Action::make('approve')->label('Duyệt')->icon('heroicon-o-check')->color('success')->visible(fn(LeaveRequest $record): bool => $record->status === RequestStatus::PENDING)->requiresConfirmation()->action(function (LeaveRequest $record): void { $result = app(LeaveServiceInterface::class)->approveLeaveRequest((string) auth()->id(), (string) $record->id); $result->isError() ? Notification::make()->title($result->getMessage())->danger()->send() : Notification::make()->title($result->getMessage())->success()->send(); }),Tables\Actions\Action::make('reject')->label('Từ chối')->icon('heroicon-o-x-mark')->color('danger')->visible(fn(LeaveRequest $record): bool => $record->status === RequestStatus::PENDING)->form([Forms\Components\Textarea::make('reason')->label('Lý do từ chối')->required()])->action(function (LeaveRequest $record, array $data): void { $result = app(LeaveServiceInterface::class)->rejectLeaveRequest((string) auth()->id(), (string) $record->id, (string) $data['reason']); $result->isError() ? Notification::make()->title($result->getMessage())->danger()->send() : Notification::make()->title($result->getMessage())->success()->send(); }),Tables\Actions\EditAction::make(),Tables\Actions\DeleteAction::make()]); }
    public static function getPages(): array { return ['index'=>Pages\ListLeaveRequests::route('/'),'create'=>Pages\CreateLeaveRequest::route('/create'),'edit'=>Pages\EditLeaveRequest::route('/{record}/edit')]; }
    private static function enumOptions(string $enum): array { return collect($enum::cases())->mapWithKeys(fn($case)=>[$case->value=>$case->label()])->all(); }
}
