<?php
namespace App\Filament\Resources;
use App\Filament\Resources\LotDepositRequestResource\Pages; use App\Modules\Area\Interfaces\LotDepositRequestServiceInterface; use App\Modules\Area\Models\Enums\LotDepositRequestStatus; use App\Modules\Area\Models\LotDepositRequest; use Filament\Forms; use Filament\Notifications\Notification; use Filament\Forms\Form; use Filament\Resources\Resource; use Filament\Tables; use Filament\Tables\Table;
class LotDepositRequestResource extends Resource
{
    protected static ?string $model=LotDepositRequest::class; protected static ?string $navigationIcon='heroicon-o-banknotes'; protected static ?string $navigationGroup='Giao dịch'; protected static ?string $modelLabel='Yêu cầu đặt cọc'; protected static ?string $pluralModelLabel='Yêu cầu đặt cọc';
    public static function form(Form $form): Form { return $form->schema([Forms\Components\Select::make('lot_id')->label('Lô đất')->relationship('lot','code')->searchable()->preload()->required(), Forms\Components\Select::make('user_id')->label('Nhân viên')->relationship('user','name')->searchable()->preload()->required(), Forms\Components\Select::make('status')->label('Trạng thái')->options(self::enumOptions(LotDepositRequestStatus::class))->required(), Forms\Components\Textarea::make('reason')->label('Lý do')->columnSpanFull(), Forms\Components\Textarea::make('reject_reason')->label('Lý do từ chối')->columnSpanFull()])->columns(2); }
    public static function table(Table $table): Table { return $table->columns([Tables\Columns\TextColumn::make('lot.code')->label('Lô')->searchable(), Tables\Columns\TextColumn::make('lot.area.name')->label('Khu'), Tables\Columns\TextColumn::make('user.name')->label('Nhân viên')->searchable(), Tables\Columns\TextColumn::make('status')->label('Trạng thái')->formatStateUsing(fn($state)=>$state instanceof LotDepositRequestStatus?$state->label():LotDepositRequestStatus::tryFrom((int)$state)?->label())->badge(), Tables\Columns\TextColumn::make('created_at')->label('Ngày tạo')->dateTime('d/m/Y H:i')->sortable()])->actions([Tables\Actions\Action::make('approve')->label('Duyệt')->icon('heroicon-o-check')->color('success')->visible(fn(LotDepositRequest $record): bool => $record->status === LotDepositRequestStatus::PENDING)->requiresConfirmation()->action(function (LotDepositRequest $record): void { $result = app(LotDepositRequestServiceInterface::class)->adminApprove((string) $record->id, auth()->user()); $result->isError() ? Notification::make()->title($result->getMessage())->danger()->send() : Notification::make()->title($result->getMessage())->success()->send(); }),Tables\Actions\Action::make('reject')->label('Từ chối')->icon('heroicon-o-x-mark')->color('danger')->visible(fn(LotDepositRequest $record): bool => $record->status === LotDepositRequestStatus::PENDING)->form([Forms\Components\Textarea::make('reason')->label('Lý do từ chối')->required()])->action(function (LotDepositRequest $record, array $data): void { $result = app(LotDepositRequestServiceInterface::class)->adminReject((string) $record->id, auth()->user(), (string) $data['reason']); $result->isError() ? Notification::make()->title($result->getMessage())->danger()->send() : Notification::make()->title($result->getMessage())->success()->send(); }),Tables\Actions\Action::make('confirm')->label('Xác nhận giao dịch')->icon('heroicon-o-banknotes')->color('warning')->visible(fn(LotDepositRequest $record): bool => $record->status === LotDepositRequestStatus::APPROVED)->requiresConfirmation()->action(function (LotDepositRequest $record): void { $result = app(LotDepositRequestServiceInterface::class)->adminConfirmTransaction((string) $record->id, auth()->user()); $result->isError() ? Notification::make()->title($result->getMessage())->danger()->send() : Notification::make()->title($result->getMessage())->success()->send(); }),Tables\Actions\EditAction::make(),Tables\Actions\DeleteAction::make()]); }
    public static function getPages(): array { return ['index'=>Pages\ListLotDepositRequests::route('/'),'create'=>Pages\CreateLotDepositRequest::route('/create'),'edit'=>Pages\EditLotDepositRequest::route('/{record}/edit')]; }
    private static function enumOptions(string $enum): array { return collect($enum::cases())->mapWithKeys(fn($case)=>[$case->value=>$case->label()])->all(); }
}
